---
language: bash

dist: trusty

env:
  - VERSION=9.4-2.2
  - VERSION=9.5-2.2

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="jpalanca/postgis-kmeans:$VERSION"

script:
  - docker build --pull -t "$image" .
  - ~/official-images/test/run.sh -c ~/official-images/test/config.sh -c ../test/postgis-config.sh "$image"
